### ISSUE TITLE
Error with running bash InferIntracellularNetwork_part1.sh

### ISSUE THREAD

**Issue by sailseem** [huBioinfo/CytoTalk#1]
![image](https://user-images.githubusercontent.com/72428172/117659285-c2a1d400-b169-11eb-9bcc-c06fde8db674.png)

Dear developer,
  This is a really good package, but when I download your cytotalke2.0 files and run the bash function in terminal, I got this error, I have no idea what it is. Could you help me with it? Thank you very much.

**Comment by sailseem** [comment]
Well,  I do copy in the CytoTalk folder, I guess it only run one part, and stuck by part II, that's the error I got, and that's the new files generated only. Please take a look here,

![image](https://user-images.githubusercontent.com/72428172/117685127-9f841e00-b183-11eb-8225-9f0d69093928.png)
![image](https://user-images.githubusercontent.com/72428172/117685207-b32f8480-b183-11eb-8722-a664d1a649b8.png)

**Comment by huBioinfo** [comment]
Based on your error messages, it seems you didn't have R installed on your system, right? So it is stuck at Step 2 in the "InferSignalingNetwork.sh". The Step 2 need to use R to parallel compute mutual information between genes.

**Comment by huBioinfo** [comment]
Thanks sailseem, actually we have just finished porting the code from Matlab to R and now testing the R version. We will release it in a few days, which will be more friendly to use. Hope you find CytoTalk useful in your project.

**Comment by sailseem** [comment]
Dear,
   I checked R version of cytoTalke (v.3.02), i got two questions, first one, No module named 'pcst_fast', but i installed it already, do i need to import or is there anything i need to set in R?   Second, it took so long when this error pops up, which means the first step and second step took so lonnngggg. Is this normal? or I am doing any setting wrong? 
Thanks

**Comment by sailseem** [comment]
Dear developer,
   Thank you for the new version of cytotalk release, but I got one problem, looks like here. Could you help me with it? Thanks
![image](https://user-images.githubusercontent.com/72428172/119263598-b2e4af80-bbad-11eb-9194-0e8fa68d3aa2.png)

**Comment by huBioinfo** [comment]
Dear sailseem,

Thanks for the usage of CytoTalk R version. I think it's probably because some required pre-installed R packages are not available. I indicated five R packages in the manual of version 3.0.2. If all those packages had been installed, can you share your generated /Output/ folder with me? Then, I can look into this problem. Thanks!

**Comment by huBioinfo** [comment]
Dear sailseem,


Hope you can receive this reply. I didn't find your comment on the Github page so I have to reply directly via email.


For the first question, I guess it's probably because you installed it on Python2 but Python3 command will be invoked using the CytoTalk v3.0.2. So please first check whether "pcst_fast" package has been appropriately installed by openning a bash command window and typing the command below.
python3   # this is a bash command.
>>>import pcst_fast   # this is a python command. Do not type ">>>".
If there is no error, this package has been successfully installed. Otherwise, I recommend using the following bash command to install it.
pip3 install pcst_fast  # this is a bash command.


You can also see the described procedure above in the manual of v3.0.2.


For the second question, as you can see an example "progress logs" in the manual of v3.0.2. There are 6 steps built in the CytoTalk. The second step (2/6) is to compute mutual information for all gene pairs in the two given cell types. So this step may take around four hours typically (using 16 logical cores). In total, CytoTalk typically costs around six hours.


Please let me know any further troubles. Thanks for supporting CytoTalk. 
















At 2021-05-23 19:34:07, "sailseem" ***@***.***> wrote:

Dear,
I checked R version of cytoTalke (v.3.02), i got two questions, first one, No module named 'pcst_fast', but i installed it already, do i need to import or is there anything i need to set in R? Second, it took so long when this error pops up, which means the first step and second step took so lonnngggg. Is this normal? or I am doing any setting wrong?
Thanks

**Comment by sailseem** [comment]
> Dear sailseem,
> 
> Thanks for the usage of CytoTalk R version. I think it's probably because some required pre-installed R packages are not available. I indicated five R packages in the manual of version 3.0.2. If all those packages had been installed, can you share your generated /Output/ folder with me? Then, I can look into this problem. Thanks!

Dear,
  I preinstalled all the R package that are needed, and this is the Output folder generated 
![image](https://user-images.githubusercontent.com/72428172/119363459-d2e2a480-bc7b-11eb-836d-24e181c755fc.png)
![image](https://user-images.githubusercontent.com/72428172/119363479-d70ec200-bc7b-11eb-98e0-e21102786847.png)

**Comment by huBioinfo** [comment]
Thanks, sailseem. Is it convenient for you to share those files in the /Output/ folder with me, or directly make an Output.zip file   and send it to me (yuxuan_hu_xd@163.com)?  Then I can see whether the same problem pops up on my side. Thanks!
