### ISSUE TITLE
Can CytoTalk be used for bulk RNAseq data?

### ISSUE THREAD

**Issue by brucewayne521** [huBioinfo/CytoTalk#7]
Dear developer,
  It is a great package to study cell-cell interactions. As Cyto Talk based on cell type-specific signaling networks, can I use it to study two interacted cells with their bulk RNAseq data?

**Comment by huBioinfo** [comment]
Dear user,
Thanks for your attention. I'm afraid CytoTalk will not work if using bulk RNAseq data because this method requires gene expression data of all cell types in a tissue microenvironment as input in order to compute cell-type-specificity of genes in a given cell type. So if you have bulk data for two cell types only, CytoTalk may be not suitable.

**Comment by brucewayne521** [comment]
Thank you for your answer!
